/*
 * This source file was generated by the Gradle 'init' task
 */
package org.yuhee.catsoneday;

public class App {
    public String getGreeting() {
        return " Hello Cats <3 ";
    }

    public static void main(String[] args) {


        System.out.println(new App().getGreeting());

	
	Cat myCat = new Cat( "Kitty", "F", "Egyptian Mau", 1, 1, "silver", "spotted", "gradints of grsy and gold" );


	System.out.println(myCat.toString());
		
	myCat.setWeight(1);
	System.out.println("Let me repeat her name in case you forgot it. Her name is " +  myCat.getName() + 
		  		". And this is a little secret, but her weight is " + myCat.getWeight() + " kg.");

	myCat.lieDown();
	myCat.groom();
	myCat.loafing();
	myCat.lookAround();
	myCat.purr();
	myCat.stretch();
	myCat.pounce();
	myCat.nuzzling();
	myCat.meowing();
	myCat.headButting();

    }
}
