package org.yuhee.catsoneday.cat;


public class BreedingSexException extends Exception {
    // Inherit from the Exception class to 'catch' that exception

        public BreedingSexException (Cat mamaCat, Cat papaCat) {
            super("Breeding Sex Exception ( " + mamaCat.getName() + " is " + mamaCat.getSex() + ". Also " + papaCat.getName() + " is " + papaCat.getSex() + ". )" );
        } // For future debugging situations that may arise, the two objects are also named

    } // If the two cats received as parameters are of the same sex, a new exception message is generated by referencing the constructor of class Exception as super and creating a new exception message

